//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Business_Object_Layer_
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        public int BillsID { get; set; }
        [Required]
        public int OrderID { get; set; }
        public int RestaurantID { get; set; }
        public double BillAmount { get; set; }
        [Required]
        public int CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderTable OrderTable { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
