//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Business_Object_Layer_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestaurantDBEntities : DbContext
    {
        public RestaurantDBEntities()
            : base("name=RestaurantDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Cuisine> Cuisines { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DiningTable> DiningTables { get; set; }
        public virtual DbSet<DiningTableTrack> DiningTableTracks { get; set; }
        public virtual DbSet<OrderTable> OrderTables { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RestaurantMenuItem> RestaurantMenuItems { get; set; }
        public virtual DbSet<VListCuisinewiseItemDetail> VListCuisinewiseItemDetails { get; set; }
    
        [DbFunction("RestaurantDBEntities", "getOrderDetailsByOrderID")]
        public virtual IQueryable<getOrderDetailsByOrderID_Result> getOrderDetailsByOrderID(Nullable<int> orderID)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<getOrderDetailsByOrderID_Result>("[RestaurantDBEntities].[getOrderDetailsByOrderID](@OrderID)", orderIDParameter);
        }
    
        public virtual ObjectResult<string> CRUD_Bills(Nullable<int> billsID, Nullable<int> orderID, string billStatus, Nullable<int> customerID, Nullable<int> query)
        {
            var billsIDParameter = billsID.HasValue ?
                new ObjectParameter("BillsID", billsID) :
                new ObjectParameter("BillsID", typeof(int));
    
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var billStatusParameter = billStatus != null ?
                new ObjectParameter("BillStatus", billStatus) :
                new ObjectParameter("BillStatus", typeof(string));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_Bills", billsIDParameter, orderIDParameter, billStatusParameter, customerIDParameter, queryParameter);
        }
    
        public virtual ObjectResult<string> CRUD_Cuisine(Nullable<int> cuisineID, Nullable<int> restaurantID, string cuisineName, Nullable<int> query)
        {
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var cuisineNameParameter = cuisineName != null ?
                new ObjectParameter("CuisineName", cuisineName) :
                new ObjectParameter("CuisineName", typeof(string));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_Cuisine", cuisineIDParameter, restaurantIDParameter, cuisineNameParameter, queryParameter);
        }
    
        public virtual ObjectResult<string> CRUD_Customer(Nullable<int> customerID, Nullable<int> restaurantID, string customerName, string mobileNo, Nullable<int> query)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_Customer", customerIDParameter, restaurantIDParameter, customerNameParameter, mobileNoParameter, queryParameter);
        }
    
        public virtual ObjectResult<string> CRUD_DiningTable(Nullable<int> diningTableID, Nullable<int> restaurantID, string location, Nullable<int> query)
        {
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_DiningTable", diningTableIDParameter, restaurantIDParameter, locationParameter, queryParameter);
        }
    
        public virtual ObjectResult<string> CRUD_DiningTableTrack(Nullable<int> diningTableTrackID, Nullable<int> diningTableID, string tableStatus, Nullable<int> query)
        {
            var diningTableTrackIDParameter = diningTableTrackID.HasValue ?
                new ObjectParameter("DiningTableTrackID", diningTableTrackID) :
                new ObjectParameter("DiningTableTrackID", typeof(int));
    
            var diningTableIDParameter = diningTableID.HasValue ?
                new ObjectParameter("DiningTableID", diningTableID) :
                new ObjectParameter("DiningTableID", typeof(int));
    
            var tableStatusParameter = tableStatus != null ?
                new ObjectParameter("TableStatus", tableStatus) :
                new ObjectParameter("TableStatus", typeof(string));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_DiningTableTrack", diningTableTrackIDParameter, diningTableIDParameter, tableStatusParameter, queryParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> CRUD_OrderTable(Nullable<int> orderID, Nullable<System.DateTime> orderDate, Nullable<int> restaurantID, Nullable<int> menuItemID, Nullable<int> itemQuantity, Nullable<int> diningTableId, string tableStatus, Nullable<int> query)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var orderDateParameter = orderDate.HasValue ?
                new ObjectParameter("OrderDate", orderDate) :
                new ObjectParameter("OrderDate", typeof(System.DateTime));
    
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var itemQuantityParameter = itemQuantity.HasValue ?
                new ObjectParameter("ItemQuantity", itemQuantity) :
                new ObjectParameter("ItemQuantity", typeof(int));
    
            var diningTableIdParameter = diningTableId.HasValue ?
                new ObjectParameter("DiningTableId", diningTableId) :
                new ObjectParameter("DiningTableId", typeof(int));
    
            var tableStatusParameter = tableStatus != null ?
                new ObjectParameter("TableStatus", tableStatus) :
                new ObjectParameter("TableStatus", typeof(string));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("CRUD_OrderTable", orderIDParameter, orderDateParameter, restaurantIDParameter, menuItemIDParameter, itemQuantityParameter, diningTableIdParameter, tableStatusParameter, queryParameter);
        }
    
        public virtual ObjectResult<string> CRUD_Restaurant(Nullable<int> restaurantID, string restaurantName, string address, string mobileNo, Nullable<int> query)
        {
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var restaurantNameParameter = restaurantName != null ?
                new ObjectParameter("RestaurantName", restaurantName) :
                new ObjectParameter("RestaurantName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_Restaurant", restaurantIDParameter, restaurantNameParameter, addressParameter, mobileNoParameter, queryParameter);
        }
    
        public virtual ObjectResult<string> CRUD_RestaurantMenuItem(Nullable<int> menuItemID, Nullable<int> cuisineID, string itemName, Nullable<double> itemPrice, Nullable<int> query)
        {
            var menuItemIDParameter = menuItemID.HasValue ?
                new ObjectParameter("MenuItemID", menuItemID) :
                new ObjectParameter("MenuItemID", typeof(int));
    
            var cuisineIDParameter = cuisineID.HasValue ?
                new ObjectParameter("CuisineID", cuisineID) :
                new ObjectParameter("CuisineID", typeof(int));
    
            var itemNameParameter = itemName != null ?
                new ObjectParameter("ItemName", itemName) :
                new ObjectParameter("ItemName", typeof(string));
    
            var itemPriceParameter = itemPrice.HasValue ?
                new ObjectParameter("ItemPrice", itemPrice) :
                new ObjectParameter("ItemPrice", typeof(double));
    
            var queryParameter = query.HasValue ?
                new ObjectParameter("Query", query) :
                new ObjectParameter("Query", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CRUD_RestaurantMenuItem", menuItemIDParameter, cuisineIDParameter, itemNameParameter, itemPriceParameter, queryParameter);
        }
    
        public virtual ObjectResult<getDaywiseAndTablewiseOrderAmount_Result> getDaywiseAndTablewiseOrderAmount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDaywiseAndTablewiseOrderAmount_Result>("getDaywiseAndTablewiseOrderAmount");
        }
    
        public virtual int getFilterByOrderByAllCustomerDetails(Nullable<int> customerID, string customerName, string mobileNo, Nullable<int> orderID, Nullable<int> restaurantID, Nullable<int> itemQuantity, Nullable<double> orderAmount, Nullable<int> diningTableId, string restaurantName, string location)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(int));
    
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            var itemQuantityParameter = itemQuantity.HasValue ?
                new ObjectParameter("ItemQuantity", itemQuantity) :
                new ObjectParameter("ItemQuantity", typeof(int));
    
            var orderAmountParameter = orderAmount.HasValue ?
                new ObjectParameter("OrderAmount", orderAmount) :
                new ObjectParameter("OrderAmount", typeof(double));
    
            var diningTableIdParameter = diningTableId.HasValue ?
                new ObjectParameter("DiningTableId", diningTableId) :
                new ObjectParameter("DiningTableId", typeof(int));
    
            var restaurantNameParameter = restaurantName != null ?
                new ObjectParameter("RestaurantName", restaurantName) :
                new ObjectParameter("RestaurantName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getFilterByOrderByAllCustomerDetails", customerIDParameter, customerNameParameter, mobileNoParameter, orderIDParameter, restaurantIDParameter, itemQuantityParameter, orderAmountParameter, diningTableIdParameter, restaurantNameParameter, locationParameter);
        }
    
        public virtual ObjectResult<getListOfCurrentlyVacantTables_Result> getListOfCurrentlyVacantTables(Nullable<int> restaurantID)
        {
            var restaurantIDParameter = restaurantID.HasValue ?
                new ObjectParameter("RestaurantID", restaurantID) :
                new ObjectParameter("RestaurantID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListOfCurrentlyVacantTables_Result>("getListOfCurrentlyVacantTables", restaurantIDParameter);
        }
    
        public virtual ObjectResult<getYearwiseAndRestaurantwiseOrderAmount_Result> getYearwiseAndRestaurantwiseOrderAmount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getYearwiseAndRestaurantwiseOrderAmount_Result>("getYearwiseAndRestaurantwiseOrderAmount");
        }
    
        public virtual int sp_CustomerDetails(string customerName, string restaurantName, string location)
        {
            var customerNameParameter = customerName != null ?
                new ObjectParameter("CustomerName", customerName) :
                new ObjectParameter("CustomerName", typeof(string));
    
            var restaurantNameParameter = restaurantName != null ?
                new ObjectParameter("RestaurantName", restaurantName) :
                new ObjectParameter("RestaurantName", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("Location", location) :
                new ObjectParameter("Location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CustomerDetails", customerNameParameter, restaurantNameParameter, locationParameter);
        }
    }
}
