//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL_Business_Object_Layer_
{
    using System;
    using System.Collections.Generic;
    
    public partial class VListCuisinewiseItemDetail
    {
        public string CuisineName { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> ItemPrice { get; set; }
    }
}
